### ISSUE TITLE
use a german capable POS tagger

### ISSUE THREAD

**Issue by RGreinacher** [Dalphi/service-ner_iterate#6]
e.g.:

- [https://github.com/alvations/nltk_cli](https://github.com/alvations/nltk_cli)
- [http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/](http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/)

**Comment by hkorte** [comment]
or OpenNLP: https://opennlp.apache.org/documentation/manual/opennlp.html#tools.postagger.tagging.cmdline
with the german maxent model: http://opennlp.sourceforge.net/models-1.5/de-pos-maxent.bin
